# **Como obter e processar dados de fundos de investimento**

**O que é um Fundo de Investimentos?**

Um fundo de investimentos funciona como uma espécie de condomínio.

Dentro de um fundo temos vários segmentos:

Existe a empresa administradora do fundo, o gestor, os profissionais que fazem a auditoria sobre os números do fundo e, por fim, mas não menos importante, os investidores, ou nesse caso, os cotistas.

Para simplificar a compreensão de um fundo, é sempre válido pensar nele exatamente como um condomínio:

As pessoas vivem juntas em um mesmo terreno, porque assim várias coisas acabam sendo divididas. Os custos para manutenção são compartilhados, a segurança, a área de lazer e diversas outras áreas.

O fundo de investimento parte da mesma prerrogativa: Porque investir sozinho, se o investidor pode fazer isso com mais pessoas, utilizando muito mais recursos e contratando um profissional ultra qualificado para cuidar de todo esse dinheiro?

É por isso que, em grande parte, os fundos funcionam como condomínios.

Fonte: https://maisretorno.com/portal/termos/f/fundo-de-investimentos

Ferramentas importantes para ajudar a analisar e comparar fundos de investimento

Portal de dados Anbima
https://data.anbima.com.br/

Mais Retorno
https://maisretorno.com/comparacao-fundos

# **1. Extração e processamento dos dados de desempenho**

In [26]:
import pandas as pd
import plotly.express as px
import numpy as np

In [2]:
link = 'https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_202407.zip'

In [3]:
dados = pd.read_csv(link, sep=';', compression='zip')

In [4]:
dados.head()

,TP_FUNDO,CNPJ_FUNDO,DT_COMPTC,VL_TOTAL,VL_QUOTA,VL_PATRIM_LIQ,CAPTC_DIA,RESG_DIA,NR_COTST
0,FI,00.017.024/0001-53,2024-07-01,1116441.79,35.685510,1123045.70,0.0,0.0,1
1,FI,00.017.024/0001-53,2024-07-02,1116883.17,35.696761,1123399.77,0.0,0.0,1
2,FI,00.017.024/0001-53,2024-07-03,1117322.13,35.707952,1123751.97,0.0,0.0,1
3,FI,00.017.024/0001-53,2024-07-04,1117758.59,35.719066,1124101.74,0.0,0.0,1
4,FI,00.017.024/0001-53,2024-07-05,1117887.01,35.730101,1124449.01,0.0,0.0,1

In [5]:
dados.tail()

,TP_FUNDO,CNPJ_FUNDO,DT_COMPTC,VL_TOTAL,VL_QUOTA,VL_PATRIM_LIQ,CAPTC_DIA,RESG_DIA,NR_COTST
593474,FI,97.929.213/0001-34,2024-07-25,85830176.90,11.991669,85834264.75,0.0,0.0,2
593475,FI,97.929.213/0001-34,2024-07-26,86024213.90,12.018688,86027661.95,0.0,0.0,2
593476,FI,97.929.213/0001-34,2024-07-29,86057021.22,12.023181,86059828.50,0.0,0.0,2
593477,FI,97.929.213/0001-34,2024-07-30,86047233.80,12.021725,86049400.16,0.0,0.0,2
593478,FI,97.929.213/0001-34,2024-07-31,86301722.70,12.057189,86303248.19,0.0,0.0,2

### 1.2.2. Expandindo a captura para vários meses

In [6]:
i = '202401'

In [7]:
f'https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_{i}.zip'

'https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_202401.zip'

In [8]:
datas = ['202401','202402','202403',
         '202404','202405','202406',
         '202407','202408']

In [9]:
dataframes = []

for data in datas:
    url = f'https://dados.cvm.gov.br/dados/FI/DOC/INF_DIARIO/DADOS/inf_diario_fi_{data}.zip'
    dados = pd.read_csv(url, sep = ';', compression = 'zip')
    
    dataframes.append(dados)
    
    print('Extração do mês', data, 'foi concluída')
    

combine_df = pd.concat(dataframes, ignore_index=True)

Extração do mês 202401 foi concluída
Extração do mês 202402 foi concluída
Extração do mês 202403 foi concluída
Extração do mês 202404 foi concluída
Extração do mês 202405 foi concluída
Extração do mês 202406 foi concluída
Extração do mês 202407 foi concluída
Extração do mês 202408 foi concluída

In [10]:
combine_df.shape

(3978130, 9)

In [11]:
combine_df.dtypes

TP_FUNDO          object
CNPJ_FUNDO        object
DT_COMPTC         object
VL_TOTAL         float64
VL_QUOTA         float64
VL_PATRIM_LIQ    float64
CAPTC_DIA        float64
RESG_DIA         float64
NR_COTST           int64
dtype: object

In [12]:
combine_df.head()

,TP_FUNDO,CNPJ_FUNDO,DT_COMPTC,VL_TOTAL,VL_QUOTA,VL_PATRIM_LIQ,CAPTC_DIA,RESG_DIA,NR_COTST
0,FI,00.017.024/0001-53,2024-01-02,1136699.13,34.298860,1139708.10,0.0,0.0,1
1,FI,00.017.024/0001-53,2024-01-03,1137245.82,34.312303,1140154.80,0.0,0.0,1
2,FI,00.017.024/0001-53,2024-01-04,1137741.93,34.326023,1140610.71,0.0,0.0,1
3,FI,00.017.024/0001-53,2024-01-05,1138240.64,34.338221,1141016.02,0.0,0.0,1
4,FI,00.017.024/0001-53,2024-01-08,1138427.98,34.350495,1141423.89,0.0,0.0,1

In [13]:
combine_df.tail()

,TP_FUNDO,CNPJ_FUNDO,DT_COMPTC,VL_TOTAL,VL_QUOTA,VL_PATRIM_LIQ,CAPTC_DIA,RESG_DIA,NR_COTST
3978125,FI,97.929.213/0001-34,2024-08-05,86141337.29,12.034513,86140937.31,0.0,0.0,2
3978126,FI,97.929.213/0001-34,2024-08-06,86229171.38,12.046694,86228130.09,0.0,0.0,2
3978127,FI,97.929.213/0001-34,2024-08-07,86236877.27,12.054225,86282029.92,0.0,0.0,2
3978128,FI,97.929.213/0001-34,2024-08-08,86552842.38,12.098277,86597349.94,0.0,0.0,2
3978129,FI,97.929.213/0001-34,2024-08-09,86552842.38,12.098277,86597349.94,0.0,0.0,2

Filtro de CNPJ

In [14]:
combine_df.index = pd.to_datetime(combine_df.DT_COMPTC)

In [16]:
combine_df[combine_df['CNPJ_FUNDO'] == '33.212.222/0001-27']

,TP_FUNDO,CNPJ_FUNDO,DT_COMPTC,VL_TOTAL,VL_QUOTA,VL_PATRIM_LIQ,CAPTC_DIA,RESG_DIA,NR_COTST
DT_COMPTC,,,,,,,,,
2024-01-02,FI,33.212.222/0001-27,2024-01-02,2.526838e+08,1.497831,3.081944e+08,0.0,0.0,1
2024-01-03,FI,33.212.222/0001-27,2024-01-03,3.035106e+08,1.475591,3.036183e+08,0.0,0.0,1
2024-01-04,FI,33.212.222/0001-27,2024-01-04,3.007567e+08,1.462206,3.008642e+08,0.0,0.0,1
2024-01-05,FI,33.212.222/0001-27,2024-01-05,3.026030e+08,1.471190,3.027126e+08,0.0,0.0,1
2024-01-08,FI,33.212.222/0001-27,2024-01-08,3.054412e+08,1.484899,3.055335e+08,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...
2024-08-05,FI,33.212.222/0001-27,2024-08-05,2.899066e+08,1.396220,2.899623e+08,0.0,0.0,1
2024-08-06,FI,33.212.222/0001-27,2024-08-06,2.915665e+08,1.403887,2.915546e+08,0.0,0.0,1
2024-08-07,FI,33.212.222/0001-27,2024-08-07,2.924929e+08,1.408632,2.925400e+08,0.0,0.0,1
2024-08-08,FI,33.212.222/0001-27,2024-08-08,2.939321e+08,1.415553,2.939774e+08,0.0,0.0,1
2024-08-09,FI,33.212.222/0001-27,2024-08-09,2.952082e+08,1.421689,2.952517e+08,0.0,0.0,1

### Patrimônio Líquido do FUndo

In [24]:
# Filtrando os dados para o CNPJ específico
df_filtered = combine_df[combine_df['CNPJ_FUNDO'] == '33.212.222/0001-27']

# Calculando a média do Valor Patrimonial Líquido
df_filtered['Média_VL_PATRIM_LIQ'] = df_filtered['VL_PATRIM_LIQ'].mean()

# Criando o gráfico interativo
fig = px.line(df_filtered, x=df_filtered.index, y='VL_PATRIM_LIQ', title='Patrimônio Líquido do Fundo - UPGRADE FIM CP ')

# Adicionando a linha da média ao gráfico
fig.add_scatter(x=df_filtered.index, y=df_filtered['Média_VL_PATRIM_LIQ'], mode='lines', name='Média VL Patrimonial')

# Atualizando os eixos e removendo as linhas de fundo
fig.update_xaxes(title_text='Data', showgrid=False)
fig.update_yaxes(title_text='Valor Patrimonial Líquido', showgrid=False)

# Exibindo o gráfico
fig.show()

C:\Users\akira\AppData\Local\Temp\ipykernel_20684\1192769012.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Volatilidade do Fundo

In [28]:

# Filtrando os dados para o CNPJ específico
df_filtered = combine_df[combine_df['CNPJ_FUNDO'] == '33.212.222/0001-27']

# Calculando o retorno diário baseado na VL_QUOTA
df_filtered['retorno_diario'] = df_filtered['VL_QUOTA'].pct_change()

# Calculando a volatilidade em uma janela móvel de 30 dias
df_filtered['volatilidade_30d'] = df_filtered['retorno_diario'].rolling(window=30).std() * np.sqrt(252)

# Removendo valores NaN resultantes do cálculo de volatilidade nas primeiras linhas
df_filtered = df_filtered.dropna(subset=['volatilidade_30d'])

# Criando o gráfico interativo da volatilidade
fig = px.line(df_filtered, x='DT_COMPTC', y='volatilidade_30d', title='Volatilidade Anualizada (30 dias) do Fundo')

# Atualizando os eixos e removendo as linhas de fundo
fig.update_xaxes(title_text='Data', showgrid=False)
fig.update_yaxes(title_text='Volatilidade Anualizada', showgrid=False)

# Exibindo o gráfico
fig.show()

C:\Users\akira\AppData\Local\Temp\ipykernel_20684\472418499.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\akira\AppData\Local\Temp\ipykernel_20684\472418499.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

# 2. Capturação de Dados

Obtenção direto da CVM

In [33]:
url = "http://dados.cvm.gov.br/dados/FI/CAD/DADOS/cad_fi.csv"

In [34]:
cadastral = pd.read_csv(url, sep = ';', encoding = 'ISO-8859-1', low_memory = False)

In [35]:
cadastral.shape

(79739, 41)

In [36]:
cadastral.head()

,TP_FUNDO,CNPJ_FUNDO,DENOM_SOCIAL,DT_REG,DT_CONST,CD_CVM,DT_CANCEL,SIT,DT_INI_SIT,DT_INI_ATIV,...,CPF_CNPJ_GESTOR,GESTOR,CNPJ_AUDITOR,AUDITOR,CNPJ_CUSTODIANTE,CUSTODIANTE,CNPJ_CONTROLADOR,CONTROLADOR,INVEST_CEMPR_EXTER,CLASSE_ANBIMA
0,FACFIF,00.000.684/0001-21,DEUTSCHE BANK FDO APLIC QUOTAS FDO INV FINANCE...,2003-04-30,1994-12-20,19.0,2000-08-01,CANCELADA,2000-08-01,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FACFIF,00.000.731/0001-37,ITAMARITI CASH FUNDO APLICACAO QUOTAS FDOS INV...,2003-04-30,1994-05-18,40681.0,1996-01-26,CANCELADA,1996-01-26,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FACFIF,00.000.732/0001-81,FUNDO APLIC. QUOTAS DE F.I. SANTANDER CURTO PRAZO,2003-04-30,1994-05-24,27.0,1999-09-03,CANCELADA,1999-09-03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FACFIF,00.000.740/0001-28,FUNDO DE APLIC EM QUOTAS DE FUNDOS DE INV BMC ...,2003-04-30,1994-05-23,40690.0,1996-06-10,CANCELADA,1996-06-10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FACFIF,00.000.749/0001-39,BALANCE FUNDO APLICACAO QUOTAS FUNDO INVESTIME...,2003-04-30,1994-05-12,35.0,2000-06-26,CANCELADA,2000-06-26,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
cadastral = cadastral[cadastral['SIT'] != 'CANCELADA']

In [38]:
cadastral.shape

(36242, 41)

In [39]:
percent_missing = cadastral.isnull().sum()* 100 / len(cadastral)

In [40]:
percent_missing

TP_FUNDO               0.000000
CNPJ_FUNDO             0.000000
DENOM_SOCIAL           0.000000
DT_REG                 0.000000
DT_CONST               0.281441
CD_CVM                 0.013796
DT_CANCEL             99.997241
SIT                    0.000000
DT_INI_SIT             0.000000
DT_INI_ATIV            6.851167
DT_INI_EXERC           8.142487
DT_FIM_EXERC           8.142487
CLASSE                 0.424921
DT_INI_CLASSE          0.424921
RENTAB_FUNDO          25.895370
CONDOM                 0.540809
FUNDO_COTAS            0.419403
FUNDO_EXCLUSIVO       19.946471
TRIB_LPRAZO           74.833067
PUBLICO_ALVO           2.199106
ENTID_INVEST          94.779538
TAXA_PERFM            37.624855
INF_TAXA_PERFM        87.547597
TAXA_ADM              37.671762
INF_TAXA_ADM          99.685448
VL_PATRIM_LIQ          8.476353
DT_PATRIM_LIQ          8.476353
DIRETOR               20.048562
CNPJ_ADMIN             0.011037
ADMIN                  0.011037
PF_PJ_GESTOR           0.405607
CPF_CNPJ_GESTOR        0.405607
GESTOR                 0.405607
CNPJ_AUDITOR           0.618067
AUDITOR                0.618067
CNPJ_CUSTODIANTE       1.338226
CUSTODIANTE            1.338226
CNPJ_CONTROLADOR      20.169969
CONTROLADOR           20.169969
INVEST_CEMPR_EXTER    19.946471
CLASSE_ANBIMA         22.015893
dtype: float64

In [41]:
#Removendo com mais de 10% de missing
colunas_remover = percent_missing[percent_missing > 10]

In [42]:
colunas_remover.index

Index(['DT_CANCEL', 'RENTAB_FUNDO', 'FUNDO_EXCLUSIVO', 'TRIB_LPRAZO',
       'ENTID_INVEST', 'TAXA_PERFM', 'INF_TAXA_PERFM', 'TAXA_ADM',
       'INF_TAXA_ADM', 'DIRETOR', 'CNPJ_CONTROLADOR', 'CONTROLADOR',
       'INVEST_CEMPR_EXTER', 'CLASSE_ANBIMA'],
      dtype='object')

In [43]:
cadastral = cadastral.drop(columns= colunas_remover.index, axis= 1).reset_index(drop = True)

In [44]:
cadastral.shape

(36242, 27)

### Merge para gerar um dataframe só

In [45]:
fundos_df = pd.merge(combine_df, cadastral, how = 'left', on = 'CNPJ_FUNDO')

In [46]:
fundos_df.head()

,TP_FUNDO_x,CNPJ_FUNDO,DT_COMPTC,VL_TOTAL,VL_QUOTA,VL_PATRIM_LIQ_x,CAPTC_DIA,RESG_DIA,NR_COTST,TP_FUNDO_y,...,DT_PATRIM_LIQ,CNPJ_ADMIN,ADMIN,PF_PJ_GESTOR,CPF_CNPJ_GESTOR,GESTOR,CNPJ_AUDITOR,AUDITOR,CNPJ_CUSTODIANTE,CUSTODIANTE
0,FI,00.017.024/0001-53,2024-01-02,1136699.13,34.298860,1139708.10,0.0,0.0,1,FI,...,2024-08-08,60.746.948/0001-12,BANCO BRADESCO S.A.,PJ,60.746.948/0001-12,BANCO BRADESCO S.A.,61.366.936/0001-25,ERNST & YOUNG AUDITORES INDEPENDENTES S/S LTDA.,60.746.948/0001-12,BANCO BRADESCO S.A.
1,FI,00.017.024/0001-53,2024-01-03,1137245.82,34.312303,1140154.80,0.0,0.0,1,FI,...,2024-08-08,60.746.948/0001-12,BANCO BRADESCO S.A.,PJ,60.746.948/0001-12,BANCO BRADESCO S.A.,61.366.936/0001-25,ERNST & YOUNG AUDITORES INDEPENDENTES S/S LTDA.,60.746.948/0001-12,BANCO BRADESCO S.A.
2,FI,00.017.024/0001-53,2024-01-04,1137741.93,34.326023,1140610.71,0.0,0.0,1,FI,...,2024-08-08,60.746.948/0001-12,BANCO BRADESCO S.A.,PJ,60.746.948/0001-12,BANCO BRADESCO S.A.,61.366.936/0001-25,ERNST & YOUNG AUDITORES INDEPENDENTES S/S LTDA.,60.746.948/0001-12,BANCO BRADESCO S.A.
3,FI,00.017.024/0001-53,2024-01-05,1138240.64,34.338221,1141016.02,0.0,0.0,1,FI,...,2024-08-08,60.746.948/0001-12,BANCO BRADESCO S.A.,PJ,60.746.948/0001-12,BANCO BRADESCO S.A.,61.366.936/0001-25,ERNST & YOUNG AUDITORES INDEPENDENTES S/S LTDA.,60.746.948/0001-12,BANCO BRADESCO S.A.
4,FI,00.017.024/0001-53,2024-01-08,1138427.98,34.350495,1141423.89,0.0,0.0,1,FI,...,2024-08-08,60.746.948/0001-12,BANCO BRADESCO S.A.,PJ,60.746.948/0001-12,BANCO BRADESCO S.A.,61.366.936/0001-25,ERNST & YOUNG AUDITORES INDEPENDENTES S/S LTDA.,60.746.948/0001-12,BANCO BRADESCO S.A.

In [49]:
fundo = fundos_df[fundos_df['CNPJ_FUNDO']== '33.212.222/0001-27']

In [52]:
fundo.DENOM_SOCIAL.unique()

array(['UPGRADE FUNDO DE INVESTIMENTO MULTIMERCADO CRÉDITO PRIVADO'],
      dtype=object)