# 0. Noções conceituais

*Futuro de Taxa Média de Depósitos Interfinanceiros de Um Dia*

O produto

O Contrato Futuro de DI1 tem como ativo subjacente a taxa média diária dos Depósitos Interfinanceiros (DI), calculada e divulgada pela B3, compreendida entre a data de negociação, inclusive, e a data de vencimento, exclusive, e é utilizado para proteção e gerenciamento de risco de taxa de juro de ativos/passivos referenciados em DI.

(B3)

Contratos futuros de DI são a principal referência para mostrar a expectativa do mercado em relação aos próximos movimentos do Copom e ao futuro das taxas Selic e CDI.

(Infomoney)

Referências:

https://www.b3.com.br/pt_br/produtos-e-servicos/negociacao/juros/futuro-de-taxa-media-de-depositos-interfinanceiros-de-um-dia.htm
    
https://www.infomoney.com.br/ferramentas/juros-futuros-di/

![image.png](attachment:image.png)

Fonte: https://www.cnnbrasil.com.br/economia/mercado-projeta-juros-de-dois-digitos-no-brasil-por-8-anos/

A B3 divulga a cotação atualizada dos diversos contratos futuros de DI:
    
https://www.b3.com.br/pt_br/market-data-e-indices/servicos-de-dados/market-data/cotacoes/mercado-de-derivativos/?symbol=DI1

# 1. Importar as bibliotecas.

In [1]:
import pandas as pd 
import requests

In [2]:
from selenium import webdriver

from selenium.webdriver.common.by import By

from selenium.webdriver.support.ui import Select

# Inicializa o driver do navegador (sem especificar o caminho do executável)
driver = webdriver.Chrome()

In [3]:
# Abre o site
driver.get('https://www2.bmf.com.br/pages/portal/bmfbovespa/lumis/lum-boletim-online-ptBR.asp?Acao=BUSCA&cboMercadoria=DI1')

# 2. Identificando a tabela

In [4]:
driver.find_element(By.XPATH, '//*[@id="principal"]')

In [5]:
tabela = driver.find_element(By.XPATH, '//*[@id="principal"]/tbody').get_attribute('outerHTML')

In [6]:
pd.read_html(tabela, decimal = ',', thousands = '.')[3]

C:\Users\akira\AppData\Local\Temp\ipykernel_27464\27642760.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(tabela, decimal = ',', thousands = '.')[3]

    Limite Inferior  Limite Superior
0             10.05            10.77
1              9.97            10.89
2              9.91            11.04
3              9.95            11.23
4             10.02            11.46
5             10.09            11.68
6             10.21            11.86
7             10.29            11.99
8             10.35            12.11
9             10.40            12.24
10            10.46            12.36
11            10.51            12.46
12            10.62            12.62
13            10.70            12.74
14            10.75            12.84
15            10.77            12.90
16            10.77            12.93
17            10.77            12.94
18            10.78            12.96
19            10.79            12.99
20            10.81            13.03
21            10.83            13.04
22            10.84            13.06
23            10.85            13.07
24            10.86            13.10
25            10.85            13.10
26            10.85            13.10
27            10.85            13.11
28            10.87            13.13
29            10.87            13.14
30            10.86            13.13
31            10.85            13.14
32            10.83            13.11
33            10.83            13.11
34            10.81            13.09
35            10.81            13.09
36            10.81            13.09
37            10.81            13.09
38              NaN              NaN

In [7]:
list(range(0,3))

[0, 1, 2]

In [8]:
tabela1=pd.read_html(tabela, decimal = ',', thousands='.')[1]

C:\Users\akira\AppData\Local\Temp\ipykernel_27464\4115698827.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tabela1=pd.read_html(tabela, decimal = ',', thousands='.')[1]

In [9]:
tabela2 = pd.read_html(tabela, decimal = ',', thousands = '.')[2]

C:\Users\akira\AppData\Local\Temp\ipykernel_27464\2067747542.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tabela2 = pd.read_html(tabela, decimal = ',', thousands = '.')[2]

In [10]:
pd.concat([tabela1, tabela2], axis = 1)

,Contr. Aberto,Núm. Negoc.,Contr. Negoc.,Volume,Preço Exerc.,Preço Abertura,Preço Mínimo,Preço Máximo,Preço Médio,Último Preço,Últ.Of. Compra,Últ.Of. Venda,Ajuste,Sit. Ajuste,Taxa Ef.Período,Taxa Ef.Anual.(252),Ajuste Anterior
0,1706031.0,887.0,200976.0,1.997165e+10,NaN,10.41,10.40,10.41,10.41,10.40,NaN,NaN,NaN,NaN,NaN,NaN,10.41
1,3509366.0,24953.0,584653.0,5.761817e+10,NaN,10.44,10.44,10.46,10.45,10.45,NaN,NaN,NaN,NaN,NaN,NaN,10.45
2,231160.0,252.0,12792.0,1.249113e+09,NaN,10.50,10.49,10.53,10.51,10.49,NaN,NaN,NaN,NaN,NaN,NaN,10.51
3,313279.0,1133.0,50535.0,4.896172e+09,NaN,10.63,10.59,10.64,10.62,10.61,NaN,NaN,NaN,NaN,NaN,NaN,10.61
4,5996500.0,50691.0,1064580.0,1.022306e+11,NaN,10.78,10.72,10.79,10.75,10.74,NaN,NaN,NaN,NaN,NaN,NaN,10.74
5,105616.0,215.0,2355.0,2.240498e+08,NaN,10.87,10.83,10.88,10.84,10.86,NaN,NaN,NaN,NaN,NaN,NaN,10.86
6,148961.0,1.0,1.0,9.429854e+04,NaN,10.98,10.98,10.98,10.98,10.98,NaN,NaN,NaN,NaN,NaN,NaN,11.00
7,1637236.0,12013.0,197916.0,1.850159e+10,NaN,11.15,11.05,11.18,11.13,11.10,NaN,NaN,NaN,NaN,NaN,NaN,11.10
8,71151.0,127.0,3029.0,2.807304e+08,NaN,11.24,11.13,11.24,11.16,11.19,NaN,NaN,NaN,NaN,NaN,NaN,11.17
9,58629.0,4.0,161.0,1.478126e+07,NaN,11.29,11.25,11.29,11.25,11.25,NaN,NaN,NaN,NaN,NaN,NaN,11.25
10,2444091.0,33443.0,421587.0,3.834751e+10,NaN,11.40,11.26,11.43,11.36,11.31,NaN,NaN,NaN,NaN,NaN,NaN,11.32
11,35286.0,198.0,3126.0,2.814135e+08,NaN,11.47,11.33,11.49,11.42,11.36,NaN,NaN,NaN,NaN,NaN,NaN,11.37
12,918434.0,14303.0,68550.0,6.053603e+09,NaN,11.62,11.40,11.62,11.49,11.46,NaN,NaN,NaN,NaN,NaN,NaN,11.47
13,4076562.0,110949.0,1187398.0,1.018648e+11,NaN,11.65,11.46,11.77,11.60,11.53,NaN,NaN,NaN,NaN,NaN,NaN,11.54
14,568998.0,15716.0,128264.0,1.071237e+10,NaN,11.79,11.51,11.79,11.62,11.57,NaN,NaN,NaN,NaN,NaN,NaN,11.59
15,2107894.0,38595.0,215213.0,1.749555e+10,NaN,11.80,11.50,11.80,11.64,11.56,NaN,NaN,NaN,NaN,NaN,NaN,11.58
16,214631.0,2725.0,18428.0,1.453982e+09,NaN,11.81,11.51,11.82,11.64,11.55,NaN,NaN,NaN,NaN,NaN,NaN,11.57
17,2299751.0,69644.0,541673.0,4.159357e+10,NaN,11.74,11.48,11.83,11.63,11.54,NaN,NaN,NaN,NaN,NaN,NaN,11.55
18,103397.0,167.0,1223.0,9.168219e+07,NaN,11.79,11.51,11.80,11.61,11.57,NaN,NaN,NaN,NaN,NaN,NaN,11.56
19,498596.0,9231.0,55242.0,4.025189e+09,NaN,11.86,11.51,11.87,11.65,11.55,NaN,NaN,NaN,NaN,NaN,NaN,11.57
20,80952.0,330.0,4827.0,3.419847e+08,NaN,11.84,11.54,11.84,11.64,11.56,NaN,NaN,NaN,NaN,NaN,NaN,11.59
21,1225004.0,22750.0,128581.0,8.844783e+09,NaN,11.88,11.54,11.88,11.66,11.57,NaN,NaN,NaN,NaN,NaN,NaN,11.59
22,71215.0,21.0,159.0,1.066377e+07,NaN,11.72,11.58,11.72,11.63,11.59,NaN,NaN,NaN,NaN,NaN,NaN,11.61
23,105482.0,936.0,6835.0,4.450544e+08,NaN,11.86,11.57,11.88,11.71,11.60,NaN,NaN,NaN,NaN,NaN,NaN,11.62
24,30661.0,134.0,950.0,6.030007e+07,NaN,11.85,11.61,11.85,11.64,11.62,NaN,NaN,NaN,NaN,NaN,NaN,11.64
25,1112520.0,55975.0,257413.0,1.588044e+10,NaN,11.91,11.57,11.91,11.69,11.60,NaN,NaN,NaN,NaN,NaN,NaN,11.62
26,43156.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.62
27,62981.0,3.0,108.0,6.312618e+06,NaN,11.79,11.62,11.79,11.69,11.62,NaN,NaN,NaN,NaN,NaN,NaN,11.62
28,561105.0,5505.0,57736.0,3.193970e+09,NaN,11.92,11.59,11.92,11.69,11.61,NaN,NaN,NaN,NaN,NaN,NaN,11.64
29,705948.0,17732.0,86852.0,4.302764e+09,NaN,11.91,11.58,11.92,11.69,11.60,NaN,NaN,NaN,NaN,NaN,NaN,11.62
30,114091.0,72.0,2374.0,1.054822e+08,NaN,11.84,11.56,11.84,11.66,11.60,NaN,NaN,NaN,NaN,NaN,NaN,11.62
31,477340.0,11401.0,57748.0,2.297729e+09,NaN,11.88,11.56,11.90,11.66,11.59,NaN,NaN,NaN,NaN,NaN,NaN,11.61
32,36640.0,32.0,66.0,2.362510e+06,NaN,11.80,11.54,11.80,11.62,11.54,NaN,NaN,NaN,NaN,NaN,NaN,11.58
33,157679.0,2099.0,17337.0,5.558193e+08,NaN,11.81,11.54,11.83,11.64,11.56,NaN,NaN,NaN,NaN,NaN,NaN,11.57
34,21980.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.55
35,3646.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.55
36,2200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.55
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.55
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
tabela_full = tabela1

In [12]:
for i in range(1,4):
    tabela_full = pd.concat([tabela_full, pd.read_html(tabela, decimal = ',', thousands = '.')[i]], axis=1)

C:\Users\akira\AppData\Local\Temp\ipykernel_27464\118865036.py:2: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tabela_full = pd.concat([tabela_full, pd.read_html(tabela, decimal = ',', thousands = '.')[i]], axis=1)
C:\Users\akira\AppData\Local\Temp\ipykernel_27464\118865036.py:2: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tabela_full = pd.concat([tabela_full, pd.read_html(tabela, decimal = ',', thousands = '.')[i]], axis=1)
C:\Users\akira\AppData\Local\Temp\ipykernel_27464\118865036.py:2: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tabela_full = pd.concat([tabela_full, pd.read_html(tabela, decimal = ',', thousands = '.')[i]], axis=1)

In [13]:
tabela_full

,Contr. Aberto,Núm. Negoc.,Contr. Negoc.,Volume,Contr. Aberto,Núm. Negoc.,Contr. Negoc.,Volume,Preço Exerc.,Preço Abertura,...,Último Preço,Últ.Of. Compra,Últ.Of. Venda,Ajuste,Sit. Ajuste,Taxa Ef.Período,Taxa Ef.Anual.(252),Ajuste Anterior,Limite Inferior,Limite Superior
0,1706031.0,887.0,200976.0,1.997165e+10,1706031.0,887.0,200976.0,1.997165e+10,NaN,10.41,...,10.40,NaN,NaN,NaN,NaN,NaN,NaN,10.41,10.05,10.77
1,3509366.0,24953.0,584653.0,5.761817e+10,3509366.0,24953.0,584653.0,5.761817e+10,NaN,10.44,...,10.45,NaN,NaN,NaN,NaN,NaN,NaN,10.45,9.97,10.89
2,231160.0,252.0,12792.0,1.249113e+09,231160.0,252.0,12792.0,1.249113e+09,NaN,10.50,...,10.49,NaN,NaN,NaN,NaN,NaN,NaN,10.51,9.91,11.04
3,313279.0,1133.0,50535.0,4.896172e+09,313279.0,1133.0,50535.0,4.896172e+09,NaN,10.63,...,10.61,NaN,NaN,NaN,NaN,NaN,NaN,10.61,9.95,11.23
4,5996500.0,50691.0,1064580.0,1.022306e+11,5996500.0,50691.0,1064580.0,1.022306e+11,NaN,10.78,...,10.74,NaN,NaN,NaN,NaN,NaN,NaN,10.74,10.02,11.46
5,105616.0,215.0,2355.0,2.240498e+08,105616.0,215.0,2355.0,2.240498e+08,NaN,10.87,...,10.86,NaN,NaN,NaN,NaN,NaN,NaN,10.86,10.09,11.68
6,148961.0,1.0,1.0,9.429854e+04,148961.0,1.0,1.0,9.429854e+04,NaN,10.98,...,10.98,NaN,NaN,NaN,NaN,NaN,NaN,11.00,10.21,11.86
7,1637236.0,12013.0,197916.0,1.850159e+10,1637236.0,12013.0,197916.0,1.850159e+10,NaN,11.15,...,11.10,NaN,NaN,NaN,NaN,NaN,NaN,11.10,10.29,11.99
8,71151.0,127.0,3029.0,2.807304e+08,71151.0,127.0,3029.0,2.807304e+08,NaN,11.24,...,11.19,NaN,NaN,NaN,NaN,NaN,NaN,11.17,10.35,12.11
9,58629.0,4.0,161.0,1.478126e+07,58629.0,4.0,161.0,1.478126e+07,NaN,11.29,...,11.25,NaN,NaN,NaN,NaN,NaN,NaN,11.25,10.40,12.24
10,2444091.0,33443.0,421587.0,3.834751e+10,2444091.0,33443.0,421587.0,3.834751e+10,NaN,11.40,...,11.31,NaN,NaN,NaN,NaN,NaN,NaN,11.32,10.46,12.36
11,35286.0,198.0,3126.0,2.814135e+08,35286.0,198.0,3126.0,2.814135e+08,NaN,11.47,...,11.36,NaN,NaN,NaN,NaN,NaN,NaN,11.37,10.51,12.46
12,918434.0,14303.0,68550.0,6.053603e+09,918434.0,14303.0,68550.0,6.053603e+09,NaN,11.62,...,11.46,NaN,NaN,NaN,NaN,NaN,NaN,11.47,10.62,12.62
13,4076562.0,110949.0,1187398.0,1.018648e+11,4076562.0,110949.0,1187398.0,1.018648e+11,NaN,11.65,...,11.53,NaN,NaN,NaN,NaN,NaN,NaN,11.54,10.70,12.74
14,568998.0,15716.0,128264.0,1.071237e+10,568998.0,15716.0,128264.0,1.071237e+10,NaN,11.79,...,11.57,NaN,NaN,NaN,NaN,NaN,NaN,11.59,10.75,12.84
15,2107894.0,38595.0,215213.0,1.749555e+10,2107894.0,38595.0,215213.0,1.749555e+10,NaN,11.80,...,11.56,NaN,NaN,NaN,NaN,NaN,NaN,11.58,10.77,12.90
16,214631.0,2725.0,18428.0,1.453982e+09,214631.0,2725.0,18428.0,1.453982e+09,NaN,11.81,...,11.55,NaN,NaN,NaN,NaN,NaN,NaN,11.57,10.77,12.93
17,2299751.0,69644.0,541673.0,4.159357e+10,2299751.0,69644.0,541673.0,4.159357e+10,NaN,11.74,...,11.54,NaN,NaN,NaN,NaN,NaN,NaN,11.55,10.77,12.94
18,103397.0,167.0,1223.0,9.168219e+07,103397.0,167.0,1223.0,9.168219e+07,NaN,11.79,...,11.57,NaN,NaN,NaN,NaN,NaN,NaN,11.56,10.78,12.96
19,498596.0,9231.0,55242.0,4.025189e+09,498596.0,9231.0,55242.0,4.025189e+09,NaN,11.86,...,11.55,NaN,NaN,NaN,NaN,NaN,NaN,11.57,10.79,12.99
20,80952.0,330.0,4827.0,3.419847e+08,80952.0,330.0,4827.0,3.419847e+08,NaN,11.84,...,11.56,NaN,NaN,NaN,NaN,NaN,NaN,11.59,10.81,13.03
21,1225004.0,22750.0,128581.0,8.844783e+09,1225004.0,22750.0,128581.0,8.844783e+09,NaN,11.88,...,11.57,NaN,NaN,NaN,NaN,NaN,NaN,11.59,10.83,13.04
22,71215.0,21.0,159.0,1.066377e+07,71215.0,21.0,159.0,1.066377e+07,NaN,11.72,...,11.59,NaN,NaN,NaN,NaN,NaN,NaN,11.61,10.84,13.06
23,105482.0,936.0,6835.0,4.450544e+08,105482.0,936.0,6835.0,4.450544e+08,NaN,11.86,...,11.60,NaN,NaN,NaN,NaN,NaN,NaN,11.62,10.85,13.07
24,30661.0,134.0,950.0,6.030007e+07,30661.0,134.0,950.0,6.030007e+07,NaN,11.85,...,11.62,NaN,NaN,NaN,NaN,NaN,NaN,11.64,10.86,13.10
25,1112520.0,55975.0,257413.0,1.588044e+10,1112520.0,55975.0,257413.0,1.588044e+10,NaN,11.91,...,11.60,NaN,NaN,NaN,NaN,NaN,NaN,11.62,10.85,13.10
26,43156.0,NaN,NaN,NaN,43156.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.62,10.85,13.10
27,62981.0,3.0,108.0,6.312618e+06,62981.0,3.0,108.0,6.312618e+06,NaN,11.79,...,11.62,NaN,NaN,NaN,NaN,NaN,NaN,11.62,10.85,13.11
28,561105.0,5505.0,57736.0,3.193970e+09,561105.0,5505.0,57736.0,3.193970e+09,NaN,11.92,...,11.61,NaN,NaN,NaN,NaN,NaN,NaN,11.64,10.87,13.13
29,705948.0,17732.0,86852.0,4.302764e+09,705948.0,17732.0,86852.0,4.302764e+09,NaN,11.91,...,11.60,NaN,NaN,NaN,NaN,NaN,NaN,11.62,10.87,13.14
30,114091.0,72.0,2374.0,1.054822e+08,114091.0,72.0,2374.0,1.054822e+08,NaN,11.84,...,11.60,NaN,NaN,NaN,NaN,NaN,NaN,11.62,10.86,13.13
31,477340.0,11401.0,57748.0,2.297729e+09,477340.0,11401.0,57748.0,2.297729e+09,NaN,11.88,...,11.59,NaN,NaN,NaN,NaN,NaN,NaN,11.61,10.85,13.14
32,36640.0,32.0,66.0,2.362510e+06,36640.0,32.0,66.0,2.362510e+06,NaN,11.80,...,11.54,NaN,NaN,NaN,NaN,NaN,NaN,11.58,10.83,13.11
33,157679.0,2099.0,17337.0,5.558193e+08,157679.0,2099.0,17337.0,5.558193e+08,NaN,11.81,...,11.56,NaN,NaN,NaN,NaN,NaN,NaN,11.57,10.83,13.11
34,21980.0,NaN,NaN,NaN,21980.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.55,10.81,13.09
35,3646.0,NaN,NaN,NaN,3646.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.55,10.81,13.09
36,2200.0,NaN,NaN,NaN,2200.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.55,10.81,13.09
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.55,10.81,13.09
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
percent_missing = tabela_full.isnull().sum() * 100 / len(tabela_full)

In [15]:
percent_missing[percent_missing==100]

Preço Exerc.           100.0
Últ.Of. Compra         100.0
Últ.Of. Venda          100.0
Ajuste                 100.0
Sit. Ajuste            100.0
Taxa Ef.Período        100.0
Taxa Ef.Anual.(252)    100.0
dtype: float64

In [16]:
list(percent_missing[percent_missing==100].index)

['Preço Exerc.',
 'Últ.Of. Compra',
 'Últ.Of. Venda',
 'Ajuste',
 'Sit. Ajuste',
 'Taxa Ef.Período',
 'Taxa Ef.Anual.(252)']

In [17]:
[percent_missing[percent_missing==100].index]

[Index(['Preço Exerc.', 'Últ.Of. Compra', 'Últ.Of. Venda', 'Ajuste',
        'Sit. Ajuste', 'Taxa Ef.Período', 'Taxa Ef.Anual.(252)'],
       dtype='object')]

In [18]:
tabela_full.drop(list(percent_missing[percent_missing==100].index), axis = 1, inplace = True)

In [19]:
tabela_full

,Contr. Aberto,Núm. Negoc.,Contr. Negoc.,Volume,Contr. Aberto,Núm. Negoc.,Contr. Negoc.,Volume,Preço Abertura,Preço Mínimo,Preço Máximo,Preço Médio,Último Preço,Ajuste Anterior,Limite Inferior,Limite Superior
0,1706031.0,887.0,200976.0,1.997165e+10,1706031.0,887.0,200976.0,1.997165e+10,10.41,10.40,10.41,10.41,10.40,10.41,10.05,10.77
1,3509366.0,24953.0,584653.0,5.761817e+10,3509366.0,24953.0,584653.0,5.761817e+10,10.44,10.44,10.46,10.45,10.45,10.45,9.97,10.89
2,231160.0,252.0,12792.0,1.249113e+09,231160.0,252.0,12792.0,1.249113e+09,10.50,10.49,10.53,10.51,10.49,10.51,9.91,11.04
3,313279.0,1133.0,50535.0,4.896172e+09,313279.0,1133.0,50535.0,4.896172e+09,10.63,10.59,10.64,10.62,10.61,10.61,9.95,11.23
4,5996500.0,50691.0,1064580.0,1.022306e+11,5996500.0,50691.0,1064580.0,1.022306e+11,10.78,10.72,10.79,10.75,10.74,10.74,10.02,11.46
5,105616.0,215.0,2355.0,2.240498e+08,105616.0,215.0,2355.0,2.240498e+08,10.87,10.83,10.88,10.84,10.86,10.86,10.09,11.68
6,148961.0,1.0,1.0,9.429854e+04,148961.0,1.0,1.0,9.429854e+04,10.98,10.98,10.98,10.98,10.98,11.00,10.21,11.86
7,1637236.0,12013.0,197916.0,1.850159e+10,1637236.0,12013.0,197916.0,1.850159e+10,11.15,11.05,11.18,11.13,11.10,11.10,10.29,11.99
8,71151.0,127.0,3029.0,2.807304e+08,71151.0,127.0,3029.0,2.807304e+08,11.24,11.13,11.24,11.16,11.19,11.17,10.35,12.11
9,58629.0,4.0,161.0,1.478126e+07,58629.0,4.0,161.0,1.478126e+07,11.29,11.25,11.29,11.25,11.25,11.25,10.40,12.24
10,2444091.0,33443.0,421587.0,3.834751e+10,2444091.0,33443.0,421587.0,3.834751e+10,11.40,11.26,11.43,11.36,11.31,11.32,10.46,12.36
11,35286.0,198.0,3126.0,2.814135e+08,35286.0,198.0,3126.0,2.814135e+08,11.47,11.33,11.49,11.42,11.36,11.37,10.51,12.46
12,918434.0,14303.0,68550.0,6.053603e+09,918434.0,14303.0,68550.0,6.053603e+09,11.62,11.40,11.62,11.49,11.46,11.47,10.62,12.62
13,4076562.0,110949.0,1187398.0,1.018648e+11,4076562.0,110949.0,1187398.0,1.018648e+11,11.65,11.46,11.77,11.60,11.53,11.54,10.70,12.74
14,568998.0,15716.0,128264.0,1.071237e+10,568998.0,15716.0,128264.0,1.071237e+10,11.79,11.51,11.79,11.62,11.57,11.59,10.75,12.84
15,2107894.0,38595.0,215213.0,1.749555e+10,2107894.0,38595.0,215213.0,1.749555e+10,11.80,11.50,11.80,11.64,11.56,11.58,10.77,12.90
16,214631.0,2725.0,18428.0,1.453982e+09,214631.0,2725.0,18428.0,1.453982e+09,11.81,11.51,11.82,11.64,11.55,11.57,10.77,12.93
17,2299751.0,69644.0,541673.0,4.159357e+10,2299751.0,69644.0,541673.0,4.159357e+10,11.74,11.48,11.83,11.63,11.54,11.55,10.77,12.94
18,103397.0,167.0,1223.0,9.168219e+07,103397.0,167.0,1223.0,9.168219e+07,11.79,11.51,11.80,11.61,11.57,11.56,10.78,12.96
19,498596.0,9231.0,55242.0,4.025189e+09,498596.0,9231.0,55242.0,4.025189e+09,11.86,11.51,11.87,11.65,11.55,11.57,10.79,12.99
20,80952.0,330.0,4827.0,3.419847e+08,80952.0,330.0,4827.0,3.419847e+08,11.84,11.54,11.84,11.64,11.56,11.59,10.81,13.03
21,1225004.0,22750.0,128581.0,8.844783e+09,1225004.0,22750.0,128581.0,8.844783e+09,11.88,11.54,11.88,11.66,11.57,11.59,10.83,13.04
22,71215.0,21.0,159.0,1.066377e+07,71215.0,21.0,159.0,1.066377e+07,11.72,11.58,11.72,11.63,11.59,11.61,10.84,13.06
23,105482.0,936.0,6835.0,4.450544e+08,105482.0,936.0,6835.0,4.450544e+08,11.86,11.57,11.88,11.71,11.60,11.62,10.85,13.07
24,30661.0,134.0,950.0,6.030007e+07,30661.0,134.0,950.0,6.030007e+07,11.85,11.61,11.85,11.64,11.62,11.64,10.86,13.10
25,1112520.0,55975.0,257413.0,1.588044e+10,1112520.0,55975.0,257413.0,1.588044e+10,11.91,11.57,11.91,11.69,11.60,11.62,10.85,13.10
26,43156.0,NaN,NaN,NaN,43156.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.62,10.85,13.10
27,62981.0,3.0,108.0,6.312618e+06,62981.0,3.0,108.0,6.312618e+06,11.79,11.62,11.79,11.69,11.62,11.62,10.85,13.11
28,561105.0,5505.0,57736.0,3.193970e+09,561105.0,5505.0,57736.0,3.193970e+09,11.92,11.59,11.92,11.69,11.61,11.64,10.87,13.13
29,705948.0,17732.0,86852.0,4.302764e+09,705948.0,17732.0,86852.0,4.302764e+09,11.91,11.58,11.92,11.69,11.60,11.62,10.87,13.14
30,114091.0,72.0,2374.0,1.054822e+08,114091.0,72.0,2374.0,1.054822e+08,11.84,11.56,11.84,11.66,11.60,11.62,10.86,13.13
31,477340.0,11401.0,57748.0,2.297729e+09,477340.0,11401.0,57748.0,2.297729e+09,11.88,11.56,11.90,11.66,11.59,11.61,10.85,13.14
32,36640.0,32.0,66.0,2.362510e+06,36640.0,32.0,66.0,2.362510e+06,11.80,11.54,11.80,11.62,11.54,11.58,10.83,13.11
33,157679.0,2099.0,17337.0,5.558193e+08,157679.0,2099.0,17337.0,5.558193e+08,11.81,11.54,11.83,11.64,11.56,11.57,10.83,13.11
34,21980.0,NaN,NaN,NaN,21980.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.55,10.81,13.09
35,3646.0,NaN,NaN,NaN,3646.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.55,10.81,13.09
36,2200.0,NaN,NaN,NaN,2200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.55,10.81,13.09
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.55,10.81,13.09
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 4. Plotando a curva de Juros